
stages:
  - build
  - test
  - deploy
 
Build:
  image: node:17.0.3
  stage: build
  script:
    - npm install
    - echo "BUILD SUCCESSFUL APP"
 
Test:
  stage: test
  script:
    - echo "All test Passed"
 
deploy:
  stage: deploy
  image: node:17.3.0
  script:
    - npm install
    - aws s3 cp . s3://glass-shop-codepipeline-deployment/ --recursive
 