
stages:
  - build
  - test
  - deploy
 
Build:
  image: node:17.3.0
  stage: build
  script:
    - npm install
    - echo "BUILD SUCCESSFUL APP"
 
Test:
  image: node:17.3.0
  stage: test
  script:
    - echo "All test Passed"
 
deploy:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
    - aws s3 s3://glass-shop-codepipeline-deployment/ --recursive
 