stages:
  - build
  - test
  - deploy
 
Build:
  image: node:17.3.0
  stage: build
  script:
    - cd Backend
    - npm install
    - echo "BUILD SUCCESSFUL APP"
  artifacts:
    paths:
      - Backend/
 
Test:
  image: node:17.3.0
  stage: test
  script:
    - echo "All test Passed"
 
deploy:
  stage: deploy
  image: python:latest
  before-script:
    - apt-get update && apt-get install
    - pip install --upgrade pip
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION

  script:
    - cd ./Backend
    - aws s3 cp . s3://glass-shop-codepipeline-deployment/ --recursive