stages:
  - build
  - test
  - deploy
 
Build:
  image: node:17.3.0
  stage: build
  script:
    - npm install
    - echo "BUILD SUCCESSFUL APP"
  artifacts:
    paths:
      - backend/
 
Test:
  image: node:17.3.0
  stage: test
  script:
    - echo "All test Passed"
 
deploy:
  stage: deploy
  image: python:latest
  script:
    - pip install --upgrade pip
    - pip install awscli
    - cd ./backend
    - aws s3 cp . s3://glass-shop-codepipeline-deployment/ --recursive